main: infinity.minecraft.Main
name: TestPlugin
version: 1.0
author: ZoneInfinity
api-version: 1.16

commands:
  hello:
    description: Sends Greetings
  heal:
    description: Heals the Person
  wild:
    description: Teleports the player to random location
  launch:
    description: Launches you off the platform
  godboots:
    description: Gives the player god boots
  godtrident:
    description: Gives the player god trident
  airwalker:
    description: Gives the player air walker
